Force .env in github actions

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -36,7 +36,7 @@ jobs:
           echo "Waiting for PostgreSQL to be ready..."
           RETRIES=10
           COUNT=0
-          until docker compose exec -T db pg_isready -h db -p 5432 -U $DB_USER -d $DB_NAME; do
+          until docker compose --env-file backend/.env exec -T db pg_isready -h db -p 5432 -U $DB_USER -d $DB_NAME; do
             echo "PostgreSQL is unavailable - retrying... ($COUNT/$RETRIES)"
             COUNT=$((COUNT+1))
             if [ "$COUNT" -ge "$RETRIES" ]; then
@@ -49,17 +49,17 @@ jobs:
 
       - name: Run code linting
         run: |
-          docker compose exec -T backend black --check .
-          docker compose exec -T backend flake8 . || echo "Flake8 warnings detected, but not failing CI/CD."
+          docker compose --env-file backend/.env exec -T backend black --check .
+          docker compose --env-file backend/.env exec -T backend flake8 . || echo "Flake8 warnings detected, but not failing CI/CD."
 
       - name: Run migrations
         run: |
-          docker compose exec -T backend python manage.py migrate
+          docker compose --env-file backend/.env exec -T backend python manage.py migrate
 
       - name: Run tests
         run: |
-          docker compose exec -T backend pytest --cov=. --cov-report=term-missing
+          docker compose --env-file backend/.env exec -T backend pytest --cov=. --cov-report=term-missing
 
       - name: Stop Docker containers
         run: |
-          docker compose down
+          docker compose --env-file backend/.env down
