docker compose instead of docker-compose

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -42,12 +42,12 @@ jobs:
 
       - name: Build and start Docker containers
         run: |
-          docker-compose up -d
+          docker compose up -d
 
       - name: Wait for database to be ready
         run: |
           echo "Waiting for PostgreSQL to be ready..."
-          until docker-compose exec -T backend pg_isready -h postgres -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }}; do
+          until docker compose exec -T backend pg_isready -h localhost -p 5432 -U postgres -d test_db; do
             echo "PostgreSQL is unavailable - sleeping"
             sleep 2
           done
@@ -55,17 +55,17 @@ jobs:
 
       - name: Run code linting
         run: |
-          docker-compose exec -T backend black --check .
-          docker-compose exec -T backend flake8 . || echo "Flake8 warnings detected, but not failing CI/CD."
+          docker compose exec -T backend black --check .
+          docker compose exec -T backend flake8 . || echo "Flake8 warnings detected, but not failing CI/CD."
 
       - name: Run migrations
         run: |
-          docker-compose exec -T backend python manage.py migrate
+          docker compose exec -T backend python manage.py migrate
 
       - name: Run tests
         run: |
-          docker-compose exec -T backend pytest --cov=. --cov-report=term-missing
+          docker compose exec -T backend pytest --cov=. --cov-report=term-missing
 
       - name: Stop Docker containers
         run: |
-          docker-compose down
+          docker compose down
